FROM jaegertracing/all-in-one:1.49

ENV COLLECTOR_OTLP_ENABLED=true

ENV QUERY_HTTP_SERVER_HOST_PORT=0.0.0.0:${PORT}
ENV COLLECTOR_HTTP_SERVER_HOST_PORT=0.0.0.0:${PORT}

ENV MEMORY_MAX_TRACES=50000
EXPOSE 16686